version: '3'
services:
  web:
    build:
      context: docker/web
    working_dir: /var/www
    container_name: web
    ports:
      - 80:80
    volumes:
      - .:/var/www
    command: bash -c "composer -qn install && cat src/cron/crontab >> /etc/crontab && cat docker/web/php.ini.dist >> /etc/php/7.3/cli/php.ini && echo xdebug.remote_host=`ip route | awk '/default/ { print $$3 }'` >> /etc/php/7.3/cli/php.ini && cron && php -S 0.0.0.0:80 -t public"
    depends_on:
      - mariadb
      - mail
      - rabbit
      - consumers

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=svod_manager
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  consumers:
    build:
      context: docker/web
    working_dir: /var/www
    container_name: consumers
    volumes:
      - .:/var/www
    command: bash -c "composer -qn install && bin/console app:workers:run && while true; do sleep 1; done"

volumes:
  db_data:
  rabbit_data:
