version: '3'
services:
  web:
    build: 
      context: docker/web
    working_dir: /var/www
    container_name: web
    ports:
      - 80:80
    volumes:
      - .:/var/www
    command: bash -c "composer -qn install && php -S 0.0.0.0:80 -t public 2>/dev/null"
    depends_on:
      - mariadb
      - mail
  
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=svod_manager
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  # consumer:
    # conta
volumes:
  db_data:
  rabbit_data: